name: Daily Article

on:
  schedule:
    - cron: "0 6 * * *"   # 06:00 UTC = 08:00 Paris
  workflow_dispatch: {}    # <- permet le Run manuel

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Debug tree
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f | sort

      - name: Run generator
        run: |
          python3 scripts/generate_article.py

      - name: Debug changes
        run: |
          echo "=== git status ==="
          git status
          echo "=== diff index.html (head) ==="
          git --no-pager diff -- index.html | sed -n '1,120p' || true
          echo "=== tail index.html ==="
          tail -n 5 index.html || true
          echo "=== ls -la (racine) ==="
          ls -la

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html article_exemple.html
          git diff --cached --quiet && echo "No changes" || (git commit -m "Daily: inject card + timestamp" && git push)

         

   
